### PR TITLE
use C++11

### LINKED ISSUE #7: Tests fail to build: `error: exponent has no digits`
See https://github.com/acxz/pkgbuilds/issues/37

Trying to `make install` `code-eli` results in the following errors:
```
In file included from /build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_test.cpp:28:
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:17: warning: use
   of C++17 hexadecimal floating constant
 4329 |           pt << 0x1.001391762278p-2, -0x1.8951f245bb4f1p-9, 0x1.00093dc6b03
c1p-3;
      |                 ^~~~~~~~~~~~~~~~~
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:17: error: exponent
   has no digits
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:39: warning: use
   of C++17 hexadecimal floating constant
 4329 |           pt << 0x1.001391762278p-2, -0x1.8951f245bb4f1p-9, 0x1.00093dc6b03
c1p-3;
      |                                       ^~~~~~~~~~~~~~~~~~
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:39: error: exponent
   has no digits
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:61: warning: use
   of C++17 hexadecimal floating constant
 4329 |           pt << 0x1.001391762278p-2, -0x1.8951f245bb4f1p-9, 0x1.00093dc6b03c1p
-3;
      |                                                             ^~~~~~~~~~~~~~~~~~

/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4329:61: error: exponent
   has no digits
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4331:17: warning: use
   of C++17 hexadecimal floating constant
 4331 |           pt << 0x1.0014bcf3232b4p-2, -0x1.76b17b575fa2ep-9, 0x1.000b94c0b1
a28p-3;
      |                 ^~~~~~~~~~~~~~~~~~
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4331:17: error: exponent
   has no digits
/build/code-eli-git/src/Code-Eli/test/geom/minimum_distance/minimum_distance_surface_test_suite.hpp:4331:40: warning: use
   of C++17 hexadecimal floating constant
 4331 |           pt << 0x1.0014bcf3232b4p-2, -0x1.76b17b575fa2ep-9, 0x1.000b94c0b1
a28p-3;
      |                                        ^~~~~~~~~~~~~~~~~~
```

Seems like this patch of code introduced the error: https://github.com/ramcdona/Code-Eli/commit/586eb3446d2553dfb33db53826db6606dcf19b98

System:
OS: Arch
GCC: 10.1.0
lastest commit off master of code-eli
cpptest: 2.0.0

### PR DESCRIPTION
**Pull request by acxz**
resolves #7

based on the suggestions of https://bugzilla.redhat.com/show_bug.cgi?id=1321986

### CODE REVIEW

**Comment by acxz** [comment]
@ramcdona can you take a look at this PR?

**Comment by ramcdona** [comment]
Thanks for the contribution.

I will certainly try it out -- I need to verify that it works on all the Travis and Appveyor builds for OpenVSP that we use to make official releases.  Sometimes debugging toolchain changes like this can take a while as fixes on one platform cause breaks on other platforms.

Most of the time, people do not actually install Code-Eli.  It is a header-only library that just needs to configure a few files to set the version number and whatnot.

Another option would be to add a flag to the CMake stuff to make all the Code-Eli tests optional.  If you are building OpenVSP, then building, installing, and running the unit tests for Code-Eli are probably not that useful.  I noticed that the code that started this process for you was a case where exact hex floating point values were included in the test framework.  These values were the result of me finding a case that caused a crash or other problem -- I built a test case around it to help in the debugging process.  Another solution would be to convert the hex FP numbers to an approximate decimal equivalent.

**Comment by acxz** [comment]
I'll wait for the Openvsp travis builds to run (do I need to do something extra?)

Yeah ideally adding the flag would be nice, but I'll worry about that solution if this doesn't work for the Travis Builds. Also I assume you will also run into this error once you test against the latest gcc version, so its better if we have a proper solution.

Thx as always for maintaining OpenVSP! Pretty soon Arch Linux will have openvsp in its binary repos and users will be able to just install it directly with the equivalent of `sudo apt install openvsp` for Arch Linux!

**Comment by acxz** [comment]
@ramcdona any progress on this PR?

**Comment by ramcdona** [comment]
I am tracking it, but I probably wasn't going to do anything with this
until I was pulling together the next release -- which I don't know how far
off it will be.

I do not expect any problem from this.

Rob

**Pull request closed without merging**
